// Generated by CoffeeScript 1.10.0
(function() {
  var onReady;

  onReady = function() {
    setTimeout(function() {
      var ref;
      return (ref = $('.J_TryApply')[0]) != null ? ref.click() : void 0;
    }, 100);
    return $('body').on('DOMSubtreeModified', function() {
      if ($('.apply-try-address-submit').length !== 0) {
        setTimeout(function() {
          return $('.apply-try-address-submit')[0].click();
        }, 100);
        return setTimeout(function() {
          return close();
        }, 3000);
      }
    });
  };

  $('body').on('DOMSubtreeModified', function() {
    if ($('.J_TryApply').length !== 0) {
      return onReady.call();
    }
  });

  myCommonToolsZ.fireActionInCondition(function() {
    return $('.apply-try-errmsg .t1').text() === '您已经申请过该试用品,看看其他试用品吧' || $('.apply-try-msg').text() === "申请结果已公布，报告收集中...";
  }, function() {
    return close();
  }, 1000);

}).call(this);

//# sourceMappingURL=certainItemContent.js.map
