// Generated by CoffeeScript 1.10.0
(function() {
  var onReady;

  onReady = function() {
    var effectiveUrls, ele, fn, i, len, mainItems;
    mainItems = $('#J_LikeCon>li>.photo>a');
    effectiveUrls = [];
    fn = function(ele) {
      if ($(ele).attr('href') !== '') {
        return effectiveUrls.push($(ele).attr('href'));
      }
    };
    for (i = 0, len = mainItems.length; i < len; i++) {
      ele = mainItems[i];
      fn(ele);
    }
    return async.mapLimit(effectiveUrls, 1, function(url, callback) {
      var w;
      w = open(url);
      return w.onunload = function() {
        return callback(null, url);
      };
    }, function(err, result) {
      console.log('done', result);
      return $("body").prepend(result + 'down');
    });
  };

  $("body").prepend('<button id = "myActionBtn">action</button>');

  setTimeout(function() {
    return $('button#myActionBtn').on('click', function() {
      return onReady();
    });
  }, 3000);

}).call(this);

//# sourceMappingURL=mainListContent.js.map
