// Generated by CoffeeScript 1.10.0
(function() {
  var myCommonToolsZ;

  myCommonToolsZ = fireActionAtDomAppear(selector, action)(function() {
    return $('body').on('DOMSubtreeModified', function() {
      if ($(selector).length !== 0) {
        return action.call();
      }
    });
  });

}).call(this);

//# sourceMappingURL=myCommonToolsZ.js.map
